### PR TITLE
Fix Elixir v1.4 warnings

### PR DESCRIPTION
**Pull request by lpil**
Thanks for this library, very useful! :)

### CODE REVIEW

**Comment by fazibear** [comment]
Thanks!

**Comment by lpil** [comment]
Thank you! :D

**Comment by lpil** [comment]
Could you release a new version with this please? :)

**Comment by fazibear** [comment]
I want to also fix #19

**Comment by lpil** [comment]
~~Would you like me to do this? :)~~

You got it :D

**Comment by fazibear** [comment]
Done. `0.1.3` released.

**Comment by lpil** [comment]
Ace! Thanks :)

**Pull request merged**
