### PR TITLE
add support for boolean option in `:ignore` config

### LINKED ISSUE #48: support for boolean values in `:ignore` config key
currently, to ignore all errors in a specific environment (such as `:test` or `:dev`), you set `:ignore` config to a simple function that returns true:

```elixir
config :airbrakex,
  ignore: fn(_error) ->
    true
  end
```

it'd be more concise / convenient to allow users to set a boolean value here instead:

```elixir
config :airbrakex, ignore: true
```

i have a [branch open with the change](https://github.com/fazibear/airbrakex/compare/master...ktravers:add-boolean-support-ignore-env). let me know if this is something you want to support, and i'll be happy to open a PR.

### PR DESCRIPTION
**Pull request by ktravers**
closes #48 

### Summary
Currently, to ignore all errors in a specific environment (such as `:test` or `:dev`), you set `:ignore` config to a function that returns true:

```elixir
config :airbrakex,
  ignore: fn(_error) ->
    true
  end
```

This PR adds support for passing a boolean value instead of a function, as a more convenient/concise option.

```elixir
config :airbrakex, ignore: true
```

### Changes

- adds boolean ignore option
- updates documentation
- adds test for boolean ignore option

/cc @fazibear

### CODE REVIEW

**Comment by ktravers** [comment]
👋 @fazibear touching base on this PR. If you don't want to introduce this functionality, please let me know, and I'll be happy to close it and its associated issue. Or please feel free to close yourself if that's easier 🙂

**Comment by fazibear** [comment]
I'm just curious, if you want to ignore ALL errors why just disable (compile out) airbrakex ?

**Comment by ktravers** [comment]
> I'm just curious, if you want to ignore ALL errors why just disable (compile out) airbrakex ?

@fazibear In our use case, we're including `airbrakex` in our default `config/config.exs` file, then overriding it in our `config/dev.exs` and `config/test.exs` files to ignore all errors. I'm not sure how to disable/compile out airbrakex without changing our config file setup altogether (to not rely on overrides).

The proposed change seemed like the most straightforward way to achieve this. But if there's an easier way I'm unaware of, that'd be even better! Apologies if I'm missing something obvious; I've been away from this project for a bit, so my Elixir skills are a bit rusty 🙇‍♀️

**Comment by ktravers** [comment]
This PR has been pretty long-lived, so I'm going to go ahead and close. Happy to re-open if necessary, but seems like there isn't too much demand for this change outside me & my old team 😅

**Pull request closed without merging**
